Assignment4 @ Dakota Condos
IntelliTect-Samples/EWU-CSCD371-2022-Winter pull request #112
Opened 2022-02-11 03:50 UTC by htran9

final version

2022-02-11 07:35 UTC, tremorris1999 commented
I will review (although too late)

2022-02-11 07:53 UTC, tremorris1999 requested changes
Overall it looks good! Aside from the two issues I pointed out, there's a few things I'd question, but I think I can chalk it up to a very different implementation of the goal here.

Your tests are thorough and the implementation looks good!

Might also be worth noting you included some binary files that weren't necessary!

2022-02-11 07:53 UTC, tremorris1999 commented on GenericsHomework/GenericsHomework/Node.cs
> +        Root = this;
Every node will appear to be the root!

2022-02-11 07:53 UTC, tremorris1999 commented on GenericsHomework/GenericsHomework/Node.cs
> +    public Node<TValue> GetLast()
Clever! This could've been useful for me.

2022-02-11 07:53 UTC, tremorris1999 commented on GenericsHomework/GenericsHomework/Node.cs
> +        Root.Next = this;
Works in this case, but if root were set properly in 2nd constructor, it would leave _at least_ 2 nodes.

2022-02-21 01:53 UTC, mmwoodfo commented on GenericsHomework/GenericsHomeworkTests/GenericsHomeworkTests.csproj
> +    <Nullable>enable</Nullable>
Make sure you enable analyzers and treat warnings as errors for both projects

2022-02-21 01:53 UTC, mmwoodfo commented on GenericsHomework/GenericsHomework/Node.cs
> +    public Node<TValue> Root;
You shouldn't really need a `root` in a typical circular linked list.

2022-02-21 01:53 UTC, closed without merging