Assignment5+6 @ZackWard-student
IntelliTect-Samples/EWU-CSCD371-2022-Winter pull request #132
Opened 2022-02-22 04:05 UTC by jmplett

2022-02-23 21:56 UTC, tnadalini reviewed
Throughout, consider using the System.Linq.Enumerable methods Zip, Count, Sort and Contains methods for testing collections.. (Preferably avoid using Microsoft.VisualStudio.TestTools.UnitTesting.CollectionAssert although that might be easier, to get a firmer grasp on additional LINQ API.)

    Implement the ISampleData.CsvRows property, loading the data from the People.csv file and returning each line as a single string. ✔
        Change the "Copy to" property on People.csv to "Copy if newer" so that the file is deployed along with your test project. ✔
        Using LINQ, skip the first row in the People.csv. ✔
        Be sure to appropriately handle resource (IDisposable) items correctly if applicable (and it may not be depending on how you implement it). ✔

    Implement IEnumerable<string> GetUniqueSortedListOfStatesGivenCsvRows() to return a sorted, unique list of states. ✔
        Use ISampleData.CsvRows for your data source. ✔
        Don't forget the list should be unique. ✔
        Sort the list alphabetically. ✔
        Include a test that leverages a hardcoded list of Spokane-based addresses. ❌
        Include a test that uses LINQ to verify the data is sorted correctly (do not use a hardcoded list). ❌

    Implement ISampleData.GetAggregateSortedListOfStatesUsingCsvRows() to return a string that contains a unique, comma separated list of states. ✔
        Use ISampleData.GetUniqueSortedListOfStatesGivenCsvRows() for your data source. ✔
        Consider "selecting" only the states and calling ToArray() to retrieve an array of all the state names. ✔
        Given the array, consider using string.Join to combine the list into a single string. ✔

    Implement the ISampleData.People property to return all the items in People.csv as Person objects ✔
        Use ISampleData.CsvRows as the source of the data. ✔
        Sort the list by State, City, Zip. (Sort the addresses first then select). ✔
        Be sure that Person.Address is also populated. ✔
        Adding null validation to all the Person and Address properties is optional.
        Consider using ISampleData.CsvRows in your test to verify your results. ✔

    Implement ISampleDate.FilterByEmailAddress(Predicate<string> filter) to return a list of names where the email address matches the filter. ✔
        Use ISampleData.People for your data source. ✔

    Implement ISampleData.GetAggregateListOfStatesGivenPeopleCollection(IEnumerable<IPerson> people) to return a string that contains a unique, comma separated list of states. ✔
        Use the people parameter from ISampleData.People property for your data source. ✔
        At a minimum, use System.Linq.Enumerable.Aggregate LINQ method to create your result. ❌
        Don't forget the list should be unique. ✔
        It is recommended that, at a minimum, you use ISampleData.GetUniqueSortedListOfStatesGivenCsvRows to validate your result.

    Given the implementation of Node in Assignment5

    Implement IEnumerable<T> to return all the items in the "circle" of items. ❌
    Add an IEnumberable<T> ChildItems(int maximum) method to Node that returns the remaining items with a maximum number of items returned less than maximum.

Extra Credit

    Implement the homework using async/await and multi-threading by defining a new SampleDataAsync class that implements IAsyncSampleData). Refactor your SampleData and SampleDataAsync classes with minimal duplication. Be sure to refactor your tests to re-use a significant amount of the test code for both implementations. ❌

Fundamentals

    Ensure you enable:
        nullable reference types is enabled ✔
        net6 targeted ✔
        C# 10.0 ✔
        and enabled .NET analyzers for both projects ✔
    For this assignment, favor using Assert.AreEqual() (the generic version) ✔
    All of the above should be unit tested ✔
    Choose simplicity over complexity ✔

2022-02-23 21:56 UTC, tnadalini commented on Assignment/Assignment/SampleData.cs
> +            return String.Join(",", states);
I feel like this could all be done in a single return line, just using .Join at the end of your line 54. I would suggest giving it a try if possible, otherwise this looks fine.

2022-02-23 21:56 UTC, tnadalini commented on Assignment/Assignment/SampleData.cs
> +            return String.Join(',', rows);
This could be done in a single statement if needed.

2022-02-23 21:56 UTC, tnadalini commented on Assignment/Assignment.Tests/SampleDataTests.cs
> +		}
This test isn't really testing that all the rows match, only the first and last indexes. Its possible the data in between the endpoints could be switched up.

2022-02-24 19:49 UTC, tremorris1999 commented
I will also review.

2022-02-24 20:17 UTC, tremorris1999 requested changes
# EWU-CSCD371-2021-Winter

## See [Docs](Docs)

## Assignment 5&6

The purpose of this assignment is to solidify your learning of:

- Lambda expressions
- LINQ with Standard Query Operators
  - Selecting (projection)
  - Filtering
  - Aggregation
  - Sorting
  - Unit testing collections.
- Implementing IEnumerable

Given the amount of material (reading and assignment), **the homework will span two weeks of class with the final submission on Thursday 2/25**. (No assignment is due Thu 2/17)

## Reading

Prior to Thu 2/15:

- Chapter 13: Delegates and Lambda Expressions
- Chapter 15: Collection Interfaces with Standard Query Operators
- Chapter 17: Building Custom Collections (You can skim the More Collection Interfaces and Primary Collection Classes sections)

Prior to Tue 2/22:

- Chapter 20: Programming with Task-Based Asynchronous Pattern
- Chapter 22: Thread Synchronization

Recommended But **Not** Required (in order of priority)

- Chapter 19: Introducing Multithreading
- Chapter 21: Iterating in Parallel
- Chapter 18: Reflection, Attributes, and Dynamic Programming
- Chapter 16: LINQ with Query Expressions
- Chapter 14: Events

## Instructions

**Throughout, consider using the `System.Linq.Enumerable` methods `Zip`, `Count`, `Sort` and `Contains` methods for testing collections.**. (Preferably avoid using `Microsoft.VisualStudio.TestTools.UnitTesting.CollectionAssert` although that might be easier, to get a firmer grasp on additional LINQ API.)

1. Implement the `ISampleData.CsvRows` property, loading the data from the `People.csv` file and returning each line as a single string. ❌✔

   - Change the "Copy to" property on People.csv to "Copy if newer" so that the file is deployed along with your test project. ❌✔
   - Using LINQ, skip the first row in the `People.csv`. ✔
   - Be sure to appropriately handle resource (`IDisposable`) items correctly if applicable (and it may not be depending on how you implement it). ❌✔

2. Implement `IEnumerable<string> GetUniqueSortedListOfStatesGivenCsvRows()` to return a **sorted**, **unique** list of states. ❌✔

   - Use `ISampleData.CsvRows` for your data source. ✔
   - Don't forget the list should be unique. ✔
   - Sort the list alphabetically. ✔
   - Include a test that leverages a hardcoded list of Spokane-based addresses. ❌
   - Include a test that uses LINQ to verify the data is sorted correctly (do not use a hardcoded list). ✔

3. Implement `ISampleData.GetAggregateSortedListOfStatesUsingCsvRows()` to return a `string` that contains a **unique**, comma separated list of states. ❌✔

   - Use `ISampleData.GetUniqueSortedListOfStatesGivenCsvRows()` for your data source. ✔
   - Consider "selecting" only the states and calling `ToArray()` to retrieve an array of all the state names. ✔
   - Given the array, consider using `string.Join` to combine the list into a single string. ✔

4. Implement the `ISampleData.People` property to return all the items in `People.csv` as `Person` objects ✔

   - Use `ISampleData.CsvRows` as the source of the data. ✔
   - Sort the list by State, City, Zip. (Sort the addresses first then select). ✔
   - Be sure that `Person.Address` is also populated. ✔
   - Adding null validation to all the `Person` and `Address` properties is **optional**.
   - Consider using `ISampleData.CsvRows` in your test to verify your results. ✔

5. Implement `ISampleDate.FilterByEmailAddress(Predicate<string> filter)` to return a list of names where the email address matches the `filter`. ❌✔

   - Use `ISampleData.People` for your data source. ✔

6. Implement `ISampleData.GetAggregateListOfStatesGivenPeopleCollection(IEnumerable<IPerson> people)` to return a `string` that contains a **unique**, comma separated list of states. ❌✔

   - Use the `people` parameter from `ISampleData.People` property for your data source. ✔
   - At a minimum, use `System.Linq.Enumerable.Aggregate` LINQ method to create your result. ✔
   - Don't forget the list should be unique. ✔
   - It is recommended that, at a minimum, you use `ISampleData.GetUniqueSortedListOfStatesGivenCsvRows` to validate your result.

7. Given the implementation of `Node` in Assignment5

- Implement `IEnumerable<T>` to return all the items in the "circle" of items. ❌ (since you used conventional iteration)
- Add an `IEnumberable<T> ChildItems(int maximum)` method to `Node` that returns the remaining items with a maximum number of items returned less than `maximum`.  

## Extra Credit

- Implement the homework using async/await and multi-threading by defining a new `SampleDataAsync` class that implements `IAsyncSampleData`). Refactor your `SampleData` and `SampleDataAsync` classes with minimal duplication. Be sure to refactor your tests to re-use a significant amount of the test code for both implementations. ❌

## Fundamentals

- Ensure you enable:
  - nullable reference types is enabled ✔
  - net6 targeted ✔
  - C# 10.0 ✔
  - and enabled .NET analyzers for both projects ✔
- For this assignment, favor using Assert.AreEqual<T>() (the generic version) ✔
- All of the above should be unit tested ❌ (missing at least one required test)
- Choose simplicity over complexity ✔

2022-02-24 20:17 UTC, tremorris1999 commented on Assignment/Assignment.Tests/SampleDataTests.cs
> +			Assert.AreEqual(50, Enumerable.Count(testData.People));
I think this is fine since _Enumerable.Count_ is technically just a static method, since it's an extension method, you're really just calling _testData.People.Count_ .

```suggestion
			Assert.AreEqual(50, testData.People.Count()));
```

2022-02-24 20:17 UTC, tremorris1999 commented on Assignment/Assignment.Tests/SampleDataTests.cs
> +			Assert.AreEqual(27,Enumerable.Count(testData.GetUniqueSortedListOfStatesGivenCsvRows()));
No need to use _Enumerable.Count_ your _testData_ now has access to that _Count_ method through IEnumerable

2022-03-10 03:44 UTC, mmwoodfo commented on Assignment/Assignment/SampleData.cs
> +            return String.Join(',', rows);
```suggestion
            return string.Join(',', rows);
```

2022-03-10 03:44 UTC, mmwoodfo commented on GenericsHomework/GenericsHomework/Node.cs
> +        public IEnumerable<Node<T>> ChildItems(int maximum)
You could probably remove this one.

2022-03-10 03:44 UTC, closed without merging