Assignment5+6
IntelliTect-Samples/EWU-CSCD371-2022-Winter pull request #134
Opened 2022-02-22 04:58 UTC by dhoxie

Partner: @xiokd

2022-02-23 21:46 UTC, MikePHaynes commented
Will review!

2022-02-23 22:10 UTC, MikePHaynes reviewed
You guys seem to be on the right track here. It looks like you have begun to implement all of the things you have missing, I did not see a unit test for the "People" property though. I did get a few messages from the compiler as well.

1. Implement the `ISampleData.CsvRows` property, loading the data from the `People.csv` file and returning each line as a single string. ✔

   - Change the "Copy to" property on People.csv to "Copy if newer" so that the file is deployed along with your test project. ✔
   - Using LINQ, skip the first row in the `People.csv`. ✔
   - Be sure to appropriately handle resource (`IDisposable`) items correctly if applicable (and it may not be depending on how you implement it). ✔

2. Implement `IEnumerable<string> GetUniqueSortedListOfStatesGivenCsvRows()` to return a **sorted**, **unique** list of states. ✔

   - Use `ISampleData.CsvRows` for your data source. ✔
   - Don't forget the list should be unique. ✔
   - Sort the list alphabetically. ✔
   - Include a test that leverages a hardcoded list of Spokane-based addresses. ❌
   - Include a test that uses LINQ to verify the data is sorted correctly (do not use a hardcoded list). ✔

3. Implement `ISampleData.GetAggregateSortedListOfStatesUsingCsvRows()` to return a `string` that contains a **unique**, comma separated list of states. ✔

   - Use `ISampleData.GetUniqueSortedListOfStatesGivenCsvRows()` for your data source. ✔
   - Consider "selecting" only the states and calling `ToArray()` to retrieve an array of all the state names. ✔
   - Given the array, consider using `string.Join` to combine the list into a single string. ✔

4. Implement the `ISampleData.People` property to return all the items in `People.csv` as `Person` objects ✔

   - Use `ISampleData.CsvRows` as the source of the data. ✔
   - Sort the list by State, City, Zip. (Sort the addresses first then select). ✔
   - Be sure that `Person.Address` is also populated. ✔
   - Adding null validation to all the `Person` and `Address` properties is **optional**.
   - Consider using `ISampleData.CsvRows` in your test to verify your results. ❌

5. Implement `ISampleDate.FilterByEmailAddress(Predicate<string> filter)` to return a list of names where the email address matches the `filter`. ✔

   - Use `ISampleData.People` for your data source. ✔

6. Implement `ISampleData.GetAggregateListOfStatesGivenPeopleCollection(IEnumerable<IPerson> people)` to return a `string` that contains a **unique**, comma separated list of states. ✔

   - Use the `people` parameter from `ISampleData.People` property for your data source. ✔
   - At a minimum, use `System.Linq.Enumerable.Aggregate` LINQ method to create your result. ✔
   - Don't forget the list should be unique. ✔
   - It is recommended that, at a minimum, you use `ISampleData.GetUniqueSortedListOfStatesGivenCsvRows` to validate your result.

7. Given the implementation of `Node` in Assignment5

- Implement `IEnumerable<T>` to return all the items in the "circle" of items. ✔
- Add an `IEnumberable<T> ChildItems(int maximum)` method to `Node` that returns the remaining items with a maximum number of items returned less than `maximum`.  

## Extra Credit

- Implement the homework using async/await and multi-threading by defining a new `SampleDataAsync` class that implements `IAsyncSampleData`). Refactor your `SampleData` and `SampleDataAsync` classes with minimal duplication. Be sure to refactor your tests to re-use a significant amount of the test code for both implementations. ❌

## Fundamentals

- Ensure you enable:
  - nullable reference types is enabled ✔
  - net6 targeted ✔
  - C# 10.0 ✔
  - and enabled .NET analyzers for both projects ✔
- For this assignment, favor using Assert.AreEqual<T>() (the generic version) ✔
- All of the above should be unit tested ❌
- Choose simplicity over complexity ✔

2022-02-23 22:12 UTC, MikePHaynes commented on Assignment/Assignment.Tests/SampleDataTest.cs
> +            SampleData sampleData = new SampleData();
This line can be simplified.

2022-02-23 22:12 UTC, MikePHaynes commented on Assignment/Assignment.Tests/SampleDataTest.cs
> +            SampleData sampleData = new SampleData();
This line can also be simplified.

2022-02-23 22:17 UTC, MikePHaynes commented on Assignment/Assignment/Node.cs
> +            if (maximum < 0) throw new ArgumentOutOfRangeException("Maximum must be greater than 0");
You should replace the "Maximum must be greater than 0" argument with one of the methods parameter names (nameof(maximum)).

2022-02-24 21:20 UTC, A-Tanner commented
I will review this

2022-02-24 22:22 UTC, A-Tanner requested changes
Implement the ISampleData.CsvRows property, loading the data from the People.csv file and returning each line as a single string. ✔

Change the "Copy to" property on People.csv to "Copy if newer" so that the file is deployed along with your test project. ✔
Using LINQ, skip the first row in the People.csv. ✔
Be sure to appropriately handle resource (IDisposable) items correctly if applicable (and it may not be depending on how you implement it). ✔
Implement IEnumerable<string> GetUniqueSortedListOfStatesGivenCsvRows() to return a sorted, unique list of states. ✔

Use ISampleData.CsvRows for your data source. ✔
Don't forget the list should be unique. ✔
Sort the list alphabetically. ✔
Include a test that leverages a hardcoded list of Spokane-based addresses. ❌✔
Include a test that uses LINQ to verify the data is sorted correctly (do not use a hardcoded list). ✔
Implement ISampleData.GetAggregateSortedListOfStatesUsingCsvRows() to return a string that contains a unique, comma separated list of states. ✔

Use ISampleData.GetUniqueSortedListOfStatesGivenCsvRows() for your data source. ✔
Consider "selecting" only the states and calling ToArray() to retrieve an array of all the state names. ✔
Given the array, consider using string.Join to combine the list into a single string. ✔
Implement the ISampleData.People property to return all the items in People.csv as Person objects ✔

Use ISampleData.CsvRows as the source of the data. ✔
Sort the list by State, City, Zip. (Sort the addresses first then select). ✔
Be sure that Person.Address is also populated. ✔
Adding null validation to all the Person and Address properties is optional.
Consider using ISampleData.CsvRows in your test to verify your results. ✔
Implement ISampleDate.FilterByEmailAddress(Predicate<string> filter) to return a list of names where the email address matches the filter. ✔

Use ISampleData.People for your data source. ✔
Implement ISampleData.GetAggregateListOfStatesGivenPeopleCollection(IEnumerable<IPerson> people) to return a string that contains a unique, comma separated list of states. ✔

Use the people parameter from ISampleData.People property for your data source. ✔
At a minimum, use System.Linq.Enumerable.Aggregate LINQ method to create your result. ✔
Don't forget the list should be unique. ✔
It is recommended that, at a minimum, you use ISampleData.GetUniqueSortedListOfStatesGivenCsvRows to validate your result.
Given the implementation of Node in Assignment5

Implement IEnumerable<T> to return all the items in the "circle" of items. ✔
Add an IEnumberable<T> ChildItems(int maximum) method to Node that returns the remaining items with a maximum number of items returned less than maximum.
❌ -->Method currently creates an infinite loop by calling itself with the same parameter
Extra Credit
Implement the homework using async/await and multi-threading by defining a new SampleDataAsync class that implements IAsyncSampleData). Refactor your SampleData and SampleDataAsync classes with minimal duplication. Be sure to refactor your tests to re-use a significant amount of the test code for both implementations. ❌
Fundamentals
Ensure you enable:
nullable reference types is enabled ✔
net6 targeted ✔
C# 10.0 ✔
and enabled .NET analyzers for both projects ✔
For this assignment, favor using Assert.AreEqual() (the generic version) ❌✔
All of the above should be unit tested ❌✔
Choose simplicity over complexity ❌✔


In summary, your tests could use a little refactoring but most of your methods are perfect.
The one exception is `Node.ChildItems` , this method generates an infinite loop!

2022-02-24 22:22 UTC, A-Tanner commented on Assignment/Assignment/Node.cs
> +            return (IEnumerable<T>)ChildItems(maximum);
This method creates an infinite loop!

2022-03-10 04:56 UTC, mmwoodfo reviewed
I think you have some good PR comments that should have been addressed.

2022-03-10 04:56 UTC, mmwoodfo commented on Assignment/Assignment/SampleData.cs
>  namespace Assignment
A general consideration, when returning an `IEnumerable`, you don't need to use `ToList` to convert your return value to a list.

2022-03-10 04:56 UTC, mmwoodfo commented on Assignment/Assignment.Tests/NodeTests.cs
> +    public class NodeTests
You could use tests in here for your IEnumerable implementation

2022-03-10 04:56 UTC, mmwoodfo commented on Assignment/Assignment.Tests/SampleDataTest.cs
> +        //private IEnumerable<Address> GetSpokaneAddresses()
You should have a test that uses a hard-coded list of Spokane addresses.
In general, you could use more tests here.

2022-03-10 04:56 UTC, closed without merging

2022-03-10 04:56 UTC, mmwoodfo commented
@dhoxie Did you do a PR review?