Assignment1
IntelliTect-Samples/EWU-CSCD371-2022-Winter pull request #27
Opened 2022-01-17 19:36 UTC by GavenElder

added feature, tests, comments. 
FINAL SUBMIT

2022-01-19 13:11 UTC, A-Tanner commented
I will review this

2022-01-19 14:12 UTC, A-Tanner requested changes
Assignment
Pull Request title includes "Assignment 1" in the title ✔
Pull Request targets Assignment 1 branch ✔
Issue 1: Application no longer crashes ❌ -->NullReferenceException on question generation
Issue 2: Unit test properly passes ✔
Extra Credit
Issue 3: Feature request implemented ❌ --> Although the present logic should work, the application crashes and therefore the feature is still unimplemented
Issue 3: Feature request unit tested ❌ -->Test has no fail conditions, does not test functionality


Feel free to email (atanner5@ewu.edu) or message me on Discord  (Ray Tanner#2916) with any questions

2022-01-19 14:12 UTC, A-Tanner commented on PrincessBrideTrivia/PrincessBrideTrivia/Program.cs
> +            return RandomQuestionGenerator(questions);
RandomQuestionGenerator is given an array of null questions, so the main throws a NullReferenceException when it goes to read the questions

2022-01-19 14:12 UTC, A-Tanner commented on PrincessBrideTrivia/PrincessBrideTrivia/Program.cs
> +        public static Question[] RandomQuestionGenerator(Question[] questions) // added feature
Style: Misleading function name; this function does not generate anything, but rather, randomizes an existing array.

2022-01-19 14:12 UTC, A-Tanner commented on PrincessBrideTrivia/PrincessBrideTrivia.Tests/ProgramTests.cs
> +
RandomizerQuestionGenerator test has no fail condition, and therefore cannot prove that the method it is testing has functional logic. Use Assert statements to generate failure conditions, and add the code to test what RandomQuestionGenerator should be doing

2022-01-19 21:19 UTC, GavenElder commented
Thank you for your PR!

2022-01-23 19:13 UTC, mmwoodfo commented on PrincessBrideTrivia/PrincessBrideTrivia.Tests/ProgramTests.cs
> +
```suggestion
            finally
            {
                File.Delete(filePath);
            }

```

This is causing errors in your code.

2022-01-23 19:13 UTC, mmwoodfo commented on PrincessBrideTrivia/PrincessBrideTrivia.Tests/ProgramTests.cs
> +                Assert.IsFalse(arrayisequal);
You can also use `CollectionAssert.AreEqual` here for your arrays. But this solution is also acceptable.

Something to consider, there is a chance that the two arrays are shuffled in the same order. A way around this is to do a few shuffles and make sure that at least two of the indexes differ.

2022-01-23 19:13 UTC, closed without merging

2022-01-23 19:28 UTC, mmwoodfo commented
@GavenElder  did you do a PR review? If so, can you provide me with the name of the student you did the review for and/or the PR #?

Thank you.

2022-01-23 20:09 UTC, GavenElder commented
Yes I did do a PR. I believe it was an older gentlemen with the last name Scott, but I'm not seeing him within the forked repositories anymore???

2022-01-23 20:13 UTC, GavenElder commented
It difficult to to see on the Github app on my phone. But I'll find it when I get home.

2022-01-24 03:20 UTC, mmwoodfo commented
@GavenElder No worries, I found it. https://github.com/IntelliTect-Samples/EWU-CSCD371-2022-Winter/pull/19
Sorry about that, they can be difficult to track down sometimes.