Assignment3
IntelliTect-Samples/EWU-CSCD371-2022-Winter pull request #75
Opened 2022-02-01 06:40 UTC by czamora7

2022-02-02 19:38 UTC, A-Tanner commented
I will review this

2022-02-02 20:43 UTC, A-Tanner requested changes
### **Fundamentals**
Ensure you enable:
nullable reference types is enabled ❌-->Need to set this in CanHazFunny.csproj
net6 targetted ✔
C# 10.0 ❌✔ -->Need to set this in CanHazFunny.csproj
and enabled .NET analyzers for both projects ❌-->Need to set this in both .csproj files
For this assignment, always use Assert.AreEqual<T>() (the generic version) ❌-->JesterTests.cs line 43 uses non generic
All of the above should be unit tested ✔-->While JokeService.GetJoke is implicitly tested through the other tests, recall that tests should be atomic where possible
Choose simplicity over complexity ✔ --> Great job! Love your names!


### **Assignment**
For this assignment do the following:

Create two interfaces. One to represent the JokeService and one interface to represent outputting the joke to the screen (Console.WriteLine). ✔
The JokeService will need to have the interface applied to it. ✔
Create an implementation of the output interface that writes out the joke to the console. ✔
Implement the Jester class. It should take in both interfaces as dependencies. These dependencies should be null checked. ✔
The Jester class TellJoke() method should retrieve a joke from the JokeService. If the joke contains "Chuck Norris", skip it and get another. The joke should be written to the output dependency. ✔
Unit test the Jester class. Code coverage should be above 90% for this class. Moq will make this significantly easier.  -->Was unable to test, due to issues on my system
Enable nullability in the .csproj files and ensure no errors or warnings: ❌ -->CanHazFunny.csproj needs nullability property

2022-02-02 20:43 UTC, A-Tanner commented on CanHazFunny/CanHazFunny.Tests/CanHazFunny.Tests.csproj
>    </PropertyGroup>
Needs to be Nullable, have LangVersion 10.0, TreatWarningsAsErrors, EnableNETAnalyzers, CodeAnalysisTreatsWarningsAsErrors

2022-02-02 20:43 UTC, A-Tanner commented on CanHazFunny/CanHazFunny/CanHazFunny.csproj
Similar to above comment. Needs to TreatWarningsAsErrors, EnableNETAnalyzers, CodeAnalysisTreatsWarningsAsErrors

2022-02-02 20:43 UTC, A-Tanner commented on CanHazFunny/CanHazFunny.Tests/JesterTests.cs
> +        Assert.AreEqual(false, _Joke.Contains("Chuck Norris"));
Use Assert.AreEqual<bool> here to comply with assignment requirement

2022-02-09 04:31 UTC, mmwoodfo commented on CanHazFunny/CanHazFunny/Program.cs
> +    static void Main(string[] args)
```suggestion
    static void Main()
```

2022-02-09 04:31 UTC, mmwoodfo commented on CanHazFunny/CanHazFunny/JokeService.cs
> +#pragma warning disable CA2234 // This required passing the system uri objects instead of strings
Instead of disabling this warning, I'd convert this string to a `URI` using `new Uri(string)`

2022-02-09 04:31 UTC, mmwoodfo commented on CanHazFunny/CanHazFunny/Jester.cs
> +    }
You should make all of these into non-nullable auto properties. You do not need a class level property for `Joke`, this can simply be a locally scoped variable to the method it's used in.

```suggestion
    private IComedian Comedian { get; set; }
    private IJokeable Jokeable { get; set; }
```

2022-02-09 04:31 UTC, mmwoodfo commented on CanHazFunny/CanHazFunny/Jester.cs
> +    }
This should take IJokeService and IComedian as dependencies and null check them.
```suggestion
    public Jester(IJokeable jokeable, IComedian comedian)
    {
        Jokeable = jokeable ?? throw new ArgumentNullException(nameof(jokeable));
        Comedian = comedian ?? throw new ArgumentNullException(nameof(comedian));
    }
```

2022-02-09 04:31 UTC, mmwoodfo commented on CanHazFunny/CanHazFunny/Jester.cs
> +        return Joke;
No need to return the joke here.

2022-02-09 04:31 UTC, mmwoodfo commented on CanHazFunny/CanHazFunny/Jester.cs
> +    public string TellJoke(Comedian comedian, JokeService jokeService)
```suggestion
    public void TellJoke(Comedian comedian, JokeService jokeService)
```
This can be void

2022-02-09 04:31 UTC, mmwoodfo commented on CanHazFunny/CanHazFunny/Jester.cs
> +        JokeService = jokeService;
These should be set in the constructor

2022-02-09 04:31 UTC, mmwoodfo commented on CanHazFunny/CanHazFunny/Jester.cs
> +        Joke = this.JokeService.GetJoke();
```suggestion
        string joke = this.JokeService.GetJoke();
```

2022-02-09 04:31 UTC, closed without merging